function tf = is_binary(type, types)

tf = ismember( type, [ ...
    types.plus, types.minus, types.star, types.f_slash, types.b_slash, types.carat ...
  , types.dot_star, types.dot_f_slash, types.dot_b_slash, types.dot_carat ...
  , types.or, types.and, types.or_or, types.and_and ...
  , types.equal_equal, types.not_equal ...
  , types.less, types.greater, types.less_equal, types.greater_equal ...
  , types.colon ...
]);

end